/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 among_us_rojo_simple.glb 
Author: ijosephpinta (https://sketchfab.com/ijosephpinta)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/among-us-rojo-simple-3f596c649e2144288ba13199fc771ad3
Title: Among Us Rojo simple
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Amongus(props) {
  const { nodes, materials } = useGLTF('assets/models/among_us_rojo_simple.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials.main_color} />
      <mesh geometry={nodes.Object_6.geometry} material={materials.main_color} position={[-0.471, -1.282, 0.002]} scale={0.441} />
      <mesh geometry={nodes.Object_8.geometry} material={materials['Material.001']} position={[0, 1.002, 0.673]} scale={[0.692, 0.466, 0.466]} />
      <mesh geometry={nodes.Object_10.geometry} material={materials.main_color} position={[0, 0.545, -1.166]} scale={[0.68, 0.765, 1.097]} />
    </group>
  )
}

useGLTF.preload('assets/models/among_us_rojo_simple.glb')
