/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 asteroid_base.glb 
Author: michael.evan.allison (https://sketchfab.com/michael.evan.allison)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/asteroid-base-7daaf08ae0ed409b8237811cf650fc07
Title: Asteroid Base
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Asteroid_base(props) {
  const { nodes, materials } = useGLTF('assets/models/asteroid_base.glb')
  return (
    <group {...props} dispose={null} rotation-y={Math.PI*3/2}>
      <mesh geometry={nodes.Object_4.geometry} material={materials.MeteorMaterial} />
      <mesh geometry={nodes.Object_5.geometry} material={materials.CutrockMaterial} />
      <mesh geometry={nodes.Object_7.geometry} material={materials.HangarMaterial} position={[-0.62, 0.525, 0.295]} />
    </group>
  )
}

useGLTF.preload('assets/models/asteroid_base.glb')
