/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\little_astronaut.glb 
Author: Rude Randal (https://sketchfab.com/Rude_Randal)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/little-astronaut-5bb793a440164595ac4cb605822b2d88
Title: Little Astronaut
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export function Little_astronaut(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('assets/models/little_astronaut.glb')

  /*
  useFrame(({ clock }) => {
    const elapsedTime = clock.getElapsedTime()
    group.current.position.x = Math.sin(elapsedTime) * 0.1
    group.current.position.y = Math.sin(elapsedTime) * 0.1
    group.current.position.z = Math.sin(elapsedTime) * 0.1
    group.current.rotation.y = elapsedTime * 0.1
  })
*/
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.531}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_4.geometry} material={materials.Character_Texture} position={[0, 1.636, -0.136]} />
          <mesh geometry={nodes.Object_6.geometry} material={materials.Character_Texture} position={[0, 3.106, 0.123]} scale={[1.468, 1.531, 1.494]} />
          <mesh geometry={nodes.Object_8.geometry} material={materials.Character_Texture} position={[0, 1.835, -1.056]} scale={[0.776, 0.394, 0.394]} />
          <mesh geometry={nodes.Object_10.geometry} material={materials.Character_Texture} position={[0, 1.91, -1.041]} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('assets/models/little_astronaut.glb')
